version: "3.8"
services:
  api:
    build: .
    ports:
      - "9000:9000"
    env_file: .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tmdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7
volumes:
  db_data:
